gb.api:
  endpoint:
    manufacturer-url: 'http://${gb.api.endpoint.base-uri}/internal/api/v1/manufacturer'
  connection:
    period: 3000 #Mills
    max-period: 5000 #Mills
    max-attempts: 3
    connect-timeout-millis: 10000
    read-timeout-millis: 30000
